# Data Ingestion Configuration
data_ingestion_config:
  kaggle_dataset_url: "ashpalsingh1525/imdb-movies-dataset"
  zip_data_dir: "zip_data"
  raw_data_dir: "raw_data"
  processed_data_dir: "processed_data"
  processed_train_data_dir: "train_data"
  processed_test_data_dir: "test_data"

training_pipeline_config:
  pipeline_name: "movie_recommendation"
  artifact_dir: "artifact"